export const BUTTONS = [
  { label: '7', type: 'digit' },
  { label: '8', type: 'digit' },
  { label: '9', type: 'digit' },
  { label: '/', type: 'op' },
  { label: '4', type: 'digit' },
  { label: '5', type: 'digit' },
  { label: '6', type: 'digit' },
  { label: '*', type: 'op' },
  { label: '1', type: 'digit' },
  { label: '2', type: 'digit' },
  { label: '3', type: 'digit' },
  { label: '-', type: 'op' },
  { label: '0', type: 'digit' },
  { label: '.', type: 'decimal' },
  { label: '+/-', type: 'toggle' },
  { label: '+', type: 'op' },
  { label: '%', type: 'mod' },
  { label: 'C', type: 'clear' },
  { label: '=', type: 'equal' },
]
